# Generated by Django 4.0.5 on 2022-06-26 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import network.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(max_length=500, verbose_name='Информация о себе')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Пол')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PostNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='images/', validators=[network.models.file_size], verbose_name='Изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/shots/', validators=[network.models.file_size])),
                ('description', models.TextField(max_length=30)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.postnet', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
